apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
  - name: "adminer-service"
    port: 8080
    targetPort: 8080
    nodePort: 31001
