apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - name: "backend-service"
    port: 8000
    targetPort: 80
    nodePort: 31000
