apiVersion: v1
kind: Service
metadata:
  labels:
    app: flower
  name: flower
spec:
  type: NodePort
  selector:
    app: flower
  ports:
  - name: "flower-service"
    port: 5555
    targetPort: 5555
    nodePort: 31002
