apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailhog
  name: mailhog
spec:
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: smtp
          containerPort: 1025
        - name: web
          containerPort: 8025
