apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
  name: mailhog
spec:
  type: NodePort
  selector:
    app: mailhog
  ports:
  - name: http
    port: 1025
    targetPort: 1025
    nodePort: 31003
  - name: web
    port: 8025
    targetPort: 8025
    nodePort: 31004
