apiVersion: v1
kind: Service
metadata:
  labels:
    app: queue
  name: queue
spec:
  type: ClusterIP
  selector:
    app: queue
  ports:
    - name: "queue-service"
      targetPort: 5672
      port: 5672